# Generated by Django 3.2.5 on 2021-07-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option_two',
        ),
    ]
